'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FlugEntity
    Public Property FluIdPk As Integer
    Public Property FluPerIdFk As Integer
    Public Property FluFlugziel As String
    Public Property FluAbflugsort As String
    Public Property FluDatum As Nullable(Of Date)
    Public Property FluStartzeitpunkt As String
    Public Property FluLandung As String
    Public Property FluAnzahlPassagiere As String

    Public Overridable Property tblPassagiere As ICollection(Of PassagierEntity) = New HashSet(Of PassagierEntity)

End Class
