'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PassagierEntity
    Public Property PaIdPk As Integer
    Public Property PaAnrede As String
    Public Property PaName As String
    Public Property PaVorname As String
    Public Property PaEMail As String
    Public Property PaFluIDFK As Nullable(Of Integer)

    Public Overridable Property tblFluege As FlugEntity

End Class
