'------------------------------------------------------------------------------
' <auto-generated>
'    Dieser Code wurde aus einer Vorlage generiert.
'
'    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
'    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PersonalEntity
    Public Property PerIdPk As Integer
    Public Property PerAnrede As String
    Public Property PerName As String
    Public Property PerVorame As String
    Public Property PerEMail As String
    Public Property PerMitarbeiter_ As Nullable(Of Boolean)

End Class
